x-app: &default-app
  build:
    context: .
    dockerfile: Dockerfile.prod
  env_file:
    - .env

services:

  web:
    <<: *default-app
    command: >
      sh -c "
      poetry run python manage.py makemigrations &&
      poetry run python manage.py migrate &&
      poetry run python manage.py tailwind build &&
      poetry run python manage.py collectstatic --noinput &&
      poetry run gunicorn randomfactdaily.wsgi:application \
        --bind 0.0.0.0:8003 \
        --workers 1 \
        --threads 2 \
      "
    ports:
      - "8003:8003"
    volumes:
      - static_data:/data/app/staticfiles
      - app_data:/data/app
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: "0.5"
        reservations:
          memory: 128M

volumes:
  static_data:
  app_data:
